"""
PDF report generation for mango-fruit disease classification results.
"""

import os
import base64
import tempfile
import textwrap
from datetime import datetime
import unicodedata

from fpdf import FPDF


# Layout constants (A4, millimetres)
IMG_W = 80
IMG_GAP = 4
COL_GAP = 6
LEFT_COL_W = 96
FOOTER_ZONE_H = 20
DISCLAIMER_LINE_H = 3.8
DISCLAIMER_TEXT = (
    "Disclaimer: This report is generated by an AI-based classification system "
    "(AA-Enet) and is intended for research purposes only. It should not replace "
    "professional agricultural advice. Always consult a qualified agronomist for "
    "crop management decisions."
)


class _ReportPDF(FPDF):
    """Custom FPDF subclass with branded header / footer."""

    def __init__(self, user_name: str):
        super().__init__()
        self.user_name = user_name

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(34, 120, 69)
        self.cell(0, 10, "Amropali Mango Fruit Disease Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(34, 120, 69)
        self.set_line_width(0.5)
        self.line(10, self.get_y() + 1, 200, self.get_y() + 1)
        self.ln(4)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 8, f"Page {self.page_no()}/{{nb}}", align="C")


def _b64_to_tempfile(b64str: str, suffix=".png") -> str:
    """Write a base64 image to a temporary file and return the path."""
    data = base64.b64decode(b64str)
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
    tmp.write(data)
    tmp.close()
    return tmp.name


def _safe_text(text: str, width: int = 70) -> str:
    """Wrap long text into lines safe for FPDF rendering."""
    if not text:
        return ""
    cleaned = " ".join(str(text).split())
    if not cleaned:
        return ""
    cleaned = unicodedata.normalize("NFKD", cleaned)
    cleaned = "".join(ch for ch in cleaned if not unicodedata.combining(ch))
    cleaned = cleaned.encode("ascii", "ignore").decode("ascii")
    return "\n".join(
        textwrap.wrap(
            cleaned,
            width=width,
            break_long_words=True,
            break_on_hyphens=False,
        )
    )


def _wrap_width(chars_per_line: int, width_mm: float) -> int:
    """Estimate wrap width from column width in millimetres."""
    return max(18, int(chars_per_line * (width_mm / 70)))


def _right_image_x(pdf: FPDF) -> float:
    """X coordinate for the right-hand image column."""
    return pdf.w - pdf.r_margin - IMG_W


def _left_column_x(pdf: FPDF) -> float:
    return pdf.l_margin


def _multi_cell_at(pdf: FPDF, x: float, y: float, w: float, h: float, text: str) -> float:
    """Render wrapped text at an absolute position and return the bottom Y."""
    pdf.set_xy(x, y)
    pdf.multi_cell(w, h, text)
    return pdf.get_y()


def _disclaimer_layout(pdf: FPDF) -> tuple[float, float]:
    """Return the Y start and height for the bottom disclaimer block."""
    width = pdf.w - pdf.l_margin - pdf.r_margin
    wrapped = _safe_text(DISCLAIMER_TEXT, width=_wrap_width(70, width))
    lines = max(1, wrapped.count("\n") + 1)
    height = lines * DISCLAIMER_LINE_H
    y_start = pdf.h - FOOTER_ZONE_H - height
    return y_start, height


def _draw_disclaimer_bottom(pdf: FPDF) -> None:
    """Pin the disclaimer to the bottom of the page, above the footer."""
    width = pdf.w - pdf.l_margin - pdf.r_margin
    wrapped = _safe_text(DISCLAIMER_TEXT, width=_wrap_width(70, width))
    y_start, _ = _disclaimer_layout(pdf)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(130, 130, 130)
    _multi_cell_at(pdf, pdf.l_margin, y_start, width, DISCLAIMER_LINE_H, wrapped)


def _draw_scores_table(
    pdf: FPDF,
    x: float,
    y: float,
    classification: dict,
) -> float:
    """Draw a compact classification table and return the bottom Y."""
    rank_w = 10
    class_w = 52
    conf_w = LEFT_COL_W - rank_w - class_w

    pdf.set_xy(x, y)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(34, 120, 69)
    pdf.cell(LEFT_COL_W, 7, "Classification Scores", new_x="LMARGIN", new_y="NEXT")

    header_y = pdf.get_y()
    pdf.set_xy(x, header_y)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(34, 120, 69)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(rank_w, 7, "#", border=1, align="C", fill=True)
    pdf.cell(class_w, 7, "Class", border=1, align="C", fill=True)
    pdf.cell(conf_w, 7, "Conf. %", border=1, align="C", fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 9)
    for i, entry in enumerate(classification["all_scores"]):
        if i == 0:
            pdf.set_fill_color(230, 245, 235)
            pdf.set_text_color(20, 80, 40)
            fill = True
        else:
            pdf.set_text_color(50, 50, 50)
            fill = False

        pdf.set_x(x)
        pdf.cell(rank_w, 6, str(i + 1), border=1, align="C", fill=fill)
        pdf.cell(class_w, 6, entry["class"], border=1, align="L", fill=fill)
        pdf.cell(
            conf_w,
            6,
            f'{entry["score"] * 100:.2f}',
            border=1,
            align="C",
            fill=fill,
            new_x="LMARGIN",
            new_y="NEXT",
        )

    return pdf.get_y() + 3


def _draw_right_images(
    pdf: FPDF,
    y: float,
    orig_path: str,
    heat_path: str,
) -> float:
    """Place original and Grad-CAM on the right column at fixed 80 mm width."""
    x = _right_image_x(pdf)
    label_h = 6

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(50, 50, 50)
    pdf.set_xy(x, y)
    pdf.cell(IMG_W, label_h, "Original Image", align="C")
    y_orig = y + label_h
    pdf.image(orig_path, x=x, y=y_orig, w=IMG_W)

    y_heat_label = y_orig + IMG_W + IMG_GAP
    pdf.set_xy(x, y_heat_label)
    pdf.cell(IMG_W, label_h, "Grad-CAM Heatmap", align="C")
    y_heat = y_heat_label + label_h
    pdf.image(heat_path, x=x, y=y_heat, w=IMG_W)

    return y_heat + IMG_W


def _draw_disease_content(
    pdf: FPDF,
    x: float,
    y: float,
    width: float,
    pred: str,
    disease_info: dict,
    page_bottom: float,
) -> float:
    """Render disease details in the remaining left-column space."""
    wrap = _wrap_width(70, width)
    cursor_y = y

    if disease_info.get("scientific_name"):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(34, 120, 69)
        cursor_y = _multi_cell_at(
            pdf,
            x,
            cursor_y,
            width,
            5,
            f"Disease Details: {pred}",
        )
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(100, 100, 100)
        cursor_y = _multi_cell_at(
            pdf,
            x,
            cursor_y + 1,
            width,
            4,
            f"Scientific name: {disease_info['scientific_name']}",
        )
        cursor_y += 2

    if disease_info.get("description"):
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(50, 50, 50)
        cursor_y = _multi_cell_at(
            pdf,
            x,
            cursor_y,
            width,
            4,
            _safe_text(disease_info["description"], width=wrap),
        )
        cursor_y += 2

    if disease_info.get("symptoms"):
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(180, 80, 30)
        cursor_y = _multi_cell_at(pdf, x, cursor_y, width, 4.5, "Symptoms")
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(50, 50, 50)
        for symptom in disease_info["symptoms"]:
            if cursor_y > page_bottom - 8:
                break
            cursor_y = _multi_cell_at(
                pdf,
                x,
                cursor_y,
                width,
                4,
                f"- {_safe_text(symptom, width=wrap - 2)}",
            )

    if disease_info.get("remedies"):
        cursor_y += 1
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(34, 120, 69)
        cursor_y = _multi_cell_at(pdf, x, cursor_y, width, 4.5, "Recommended Treatment")
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(50, 50, 50)
        for remedy in disease_info["remedies"]:
            if cursor_y > page_bottom - 8:
                break
            cursor_y = _multi_cell_at(
                pdf,
                x,
                cursor_y,
                width,
                4,
                f"+ {_safe_text(remedy, width=wrap - 2)}",
            )

    return cursor_y


def generate_report(
    user_name: str,
    original_b64: str,
    heatmap_b64: str,
    classification: dict,
    disease_info: dict = None,
) -> bytes:
    """
    Build a PDF report and return the raw bytes.

    Parameters
    ----------
    user_name : str
        Name provided by the user.
    original_b64 : str
        Base64-encoded PNG of the original fruit image.
    heatmap_b64 : str
        Base64-encoded PNG of the Grad-CAM overlay.
    classification : dict
        Output of ``classify_image``, must include
        ``predicted_class``, ``confidence``, and ``all_scores``.
    disease_info : dict, optional
        Disease information including symptoms and remedies.
    """
    disease_info = disease_info or {}

    pdf = _ReportPDF(user_name)
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=False)
    pdf.add_page()

    left_x = _left_column_x(pdf)
    disclaimer_y, _ = _disclaimer_layout(pdf)
    content_max_y = disclaimer_y - 4

    # ── Meta info ────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    now = datetime.now().strftime("%B %d, %Y  %I:%M %p")
    pdf.cell(0, 6, f"Prepared for:  {user_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Date:  {now}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # ── Prediction summary ───────────────────────────────────────────────
    pred = classification["predicted_class"]
    conf = classification["confidence"]
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(34, 120, 69)
    pdf.cell(
        0,
        8,
        f"Prediction:  {pred}  ({conf * 100:.2f}% confidence)",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(2)

    section_y = pdf.get_y()

    # ── Left column: scores table + disease content ──────────────────────
    orig_path = _b64_to_tempfile(original_b64)
    heat_path = _b64_to_tempfile(heatmap_b64)

    try:
        table_bottom = _draw_scores_table(pdf, left_x, section_y, classification)

        _draw_disease_content(
            pdf,
            left_x,
            table_bottom + 2,
            LEFT_COL_W,
            pred,
            disease_info,
            content_max_y,
        )

        # ── Right column: images at unchanged size ───────────────────────
        _draw_right_images(pdf, section_y, orig_path, heat_path)

        # ── Disclaimer pinned to page bottom ─────────────────────────────
        _draw_disclaimer_bottom(pdf)
    finally:
        os.unlink(orig_path)
        os.unlink(heat_path)

    return bytes(pdf.output())
